#ifndef ISOLATION_MONITOR_DEFS_H_INCLUDED
#define ISOLATION_MONITOR_DEFS_H_INCLUDED

#define ISOMETER_STATUS_NORMAL      0xAA
#define ISOMETER_STATUS_FAULT       0x55

#define ISOMETER_ALARM_NORMAL       0x0
#define ISOMETER_ALARM_500KOHM      0x1
#define ISOMETER_ALARM_50KOHM       0x2


#endif // ISOLATION_MONITOR_DEFS_H_INCLUDED
