#ifndef BATTERIES_DEFS_H_INCLUDED
#define BATTERIES_DEFS_H_INCLUDED

#define BATTERIES_ISO_TX_STATE_SELF_CHECK       0x0
#define BATTERIES_ISO_TX_STATE_WORKING          0x1
#define BATTERIES_ISO_TX_STATE_STOP_WORKING     0x2
#define BATTERIES_ISO_TX_STATE_DEVICE_FAILURE   0x3

#define BATTERIES_ISO_TX_ALARM_NORMAL           0x0
#define BATTERIES_ISO_TX_ALARM_LEVEL_1          0x1
#define BATTERIES_ISO_TX_ALARM_LEVEL_2          0x2
#define BATTERIES_ISO_TX_ALARM_LEVEL_3          0x3

#define BATTERY_CHR_NOT_CHARGING    0x0
#define BATTERY_CHR_CHARGING        0x1
#define BATTERY_CHR_CHARGE_FINISH   0x2
#define BATTERY_CHR_CHARGE_ERROR    0x3

#define BATTERY_RELAY_STATE_NO_RELAY    0x0
#define BATTERY_RELAY_STATE_OPEN        0x1
#define BATTERY_RELAY_STATE_CLOSE       0x2
#define BATTERY_RELAY_STATE_INVALID     0x3

#define BATTERY_FAST_COUNTER_LIMIT 7
#define BATTERY_NORMAL_COUNTER_LIMIT 17
#define BATTERY_SLOW_COUNTER_LIMIT 90

#define BATTERY_CAN_TIMEOUT  45     //Normal cycle 200ms timeout 450ms

#endif // BATTERIES_DEFS_H_INCLUDED
