#ifndef FUSI_DEFS_H_INCLUDED
#define FUSI_DEFS_H_INCLUDED

#define FUSI_OFF_FLAG    0x0
#define FUSI_ON_FLAG     0x3

#define FUSI_BUZZER_OFF         0x0
#define FUSI_BUZZER_ON          0x1
#define FUSI_BUZZER_BLINKING    0x2
#define FUSI_BUZZER_ALWAYS_OFF  0x3

#define FUSI_CHECK_ENGINE_OFF         0x0
#define FUSI_CHECK_ENGINE_ON          0x1
#define FUSI_CHECK_ENGINE_BLINKING    0x2
#define FUSI_CHECK_ENGINE_ON_2        0x3

#define FUSI_DCLINK_MIN_VOLTAGE 500
#define FUSI_DERRATING_SPEED_M  -0.00333f
#define FUSI_DERRATING_SPEED_C  2.0f
#define FUSI_CRITICAL_PRESSURE_MBAR 6000
#define FUSI_ISOLATION_WARNING_KOHM 500
#define FUSI_ISOLATION_FAULT_KOHM 350
#define FUSI_SECURE_SPEED_RPM   100
#define FUSI_SECURE_THROTTLE_PU   0.01f
#define FUSI_SECURE_LOW_VOLTAGE  22.0f
#define FUSI_SECURE_INPULSE_CHARGE_CURRENT_A  50
#define FUSI_SECURE_PRESSURE_MBAR  7000
#define FUSI_HVIL_SPEED_LIMIT_RPM 100

#define FUSI_FAST_COUNTER_LIMIT 6
#define FUSI_NORMAL_COUNTER_LIMIT 26
#define FUSI_SLOW_COUNTER_LIMIT 51

#define FUSI_AIR_START_LIMIT_10MS           18000
#define FUSI_VISON_MAX_RESPONCE_TIME_10MS   60000
#define FUSI_BATTERY_ISO_START_LIMIT_10S     3000

#define FUSI_TIMEOUT_BUZZER_ON_10MS 2000
#define FUSI_TIMEOUT_BUZZER_OFF_10MS 4000

#endif // FUSI_DEFS_H_INCLUDED
