#ifndef TELEMETRY_DEFS_H_INCLUDED
#define TELEMETRY_DEFS_H_INCLUDED

#define TELEMETRY_FUSI_CYCLE 40

#define TELEMETRY_5MIN_COUNTER_LIMIT 3001u
#define TELEMETRY_30SEC_COUNTER_LIMIT 3000u


#endif // TELEMETRY_DEFS_H_INCLUDED
