#ifndef JARVIS_DEFS_H_INCLUDED
#define JARVIS_DEFS_H_INCLUDED

#define JAR_AUX_CONVERTER_SAFE_AUX_SUP_VOLTAGE  22.0f
#define JAR_AUX_CONVERTER_SAFE_AUX_SUP_POWER    0.3f

#define JAR_AUX_CONVERTER_ERROR_NO_ERROR 0
#define JAR_AUX_CONVERTER_ERROR_ERROR    1
#define JAR_AUX_CONVERTER_ERROR_WARNING  2
#define JAR_AUX_CONVERTER_ERROR_NO_DATA  3

#define JAR_AUX_CONVERTER_PSU_NOT_READY  0
#define JAR_AUX_CONVERTER_PSU_READY      1

#define JAR_AUX_CONVERTER_STATUS_INIT_COMPLETE  0
#define JAR_AUX_CONVERTER_STATUS_INIT_ACTIVE    1
#define JAR_AUX_CONVERTER_STATUS_RSV            2
#define JAR_AUX_CONVERTER_STATUS_NO_DATA        3

#endif // JARVIS_DEFS_H_INCLUDED
